### ISSUE TITLE
Clone option not available for single Entry Type

### ISSUE THREAD

**Issue by matthillco** [verbb/cloner#1]
### Description

Channels/Structures with a single Entry Type don't get a cloning option (+) next to them. Cloning of entry types only seems possible once there are **at least two** Entry Types. 

### Steps to reproduce

1. Visit the Entry Type settings for any Channel/Structure that only has one entry type defined
2. There is no (+) Cloner option available for that Entry Type.
3. Create a new Entry Type within this section, so that there are now two Entry Types
4. Craft updates the entries for this Section and (+) Cloner functionality is now displayed next to both Entry Types.

### Additional info

- Plugin version: 1.0.1
- Craft version: Craft Solo 3.1.14

**Comment by engram-design** [comment]
Fixed in [1.0.2](https://github.com/verbb/cloner/releases/tag/1.0.2)
