### ISSUE TITLE
Site cloning jquery selector looks for "td:first" element, but the site title uses "th"

### ISSUE THREAD

**Issue by Gaspadlo** [verbb/cloner#14]
### Describe the bug

Cloning a site on latest craftCms 4 version ends up with a js error 

![image](https://user-images.githubusercontent.com/4014669/194705277-a660e4b8-59b1-4458-ab44-d824b8bacbac.png)
![image](https://user-images.githubusercontent.com/4014669/194705279-20b6d371-c746-4c07-b53c-d70772f0932f.png)
![image](https://user-images.githubusercontent.com/4014669/194705442-5b5ffee1-e782-449a-aaa6-d71ec888da26.png)

### Steps to reproduce

1. click on a + button to clone a site on latest craftCMS version

### Craft CMS version

4.2.5.2

### Plugin version

2.0.2

### Multi-site?

YES

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/cloner/releases/tag/2.0.3)
