### ISSUE TITLE
CraftCMS 5 || Cloning Entry Types

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/cloner#16]
### Describe the bug

Looking at the docs they say Cloner works on entry types, but there's no + sign for entryTypes:

![Screenshot 2024-05-25 at 3 16 15 PM](https://github.com/verbb/cloner/assets/39201467/24e01c7d-a6b0-4261-b035-c6544ce7dae8)

Normally wouldn't the `+` be next to the `X`? Cloner works for the Sections but not for the Entry Types

### Steps to reproduce

1. Visit the Entry Types
2. You won't see the + sign

### Craft CMS version

5.1.6

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Ah, I did mean to circle back to this for Craft 5. This is a little tricky as this uses Vue in an asynchronous manner and there's a searchable table, which is unlike any of the other "static" settings. But, I think I've managed to figure something out.

Fixed for the next release. To get this early, run `composer require verbb/cloner:"dev-craft-5 as 3.0.0"`.

**Comment by DynamiteGoesBoom** [comment]
@engram-design thanks, that did the trick!

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/cloner/releases/tag/3.0.1)
