### ISSUE TITLE
Add support for Entry Types

### ISSUE THREAD

**Issue by benfeather** [verbb/cloner#17]
### What are you trying to do?

Craft 5 has separated Sections and Entry Types. 

Sections can be cloned with this plugin but entry types can't be, could this be added?

**Comment by engram-design** [comment]
Duplicate of https://github.com/verbb/cloner/issues/16 will tag a release shortly

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/cloner/releases/tag/3.0.1)
