### ISSUE TITLE
Sections and fields with german Umlauts are not cloned

### ISSUE THREAD

**Issue by bitboxfw** [verbb/cloner#2]
### Description

If an section has an german Umlaut like Ü Ö Ä or ü ö ä in the name, the section will not cloned.
If an field within the section has an Umlaut, no fields will be cloned.

### Steps to reproduce

1. Create a section or field with the name Überschrift
2. Try to clone it

### Additional info

- Plugin version: 1.0.2
- Craft version: 3.1.26

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/cloner/releases/tag/1.0.3)
