### ISSUE TITLE
Clone angell-co/Spoon group field layouts

### ISSUE THREAD

**Issue by jamielaughton** [verbb/cloner#4]
### Description

Is it possible to retain the group field layouts created using the 'Spoon' plugin when cloning sections or would this be something that could be implemented?

Cheers,
Jamie

**Comment by engram-design** [comment]
Probably requires a bit more of a in-depth look at how Spoon sets up its group field layouts, but currently its not possible.

**Comment by engram-design** [comment]
Going to close this due to Spoon being marked as [retired](https://plugins.craftcms.com/spoon?craft4)
