### ISSUE TITLE
Cloner doesn't copy over UI elements  

### ISSUE THREAD

**Issue by terryupton** [verbb/cloner#6]
**Description**
In the new Craft 3.5 it is possible to add ui elements into the tabs.
Things like (headings, tips, warnings etc)

When using cloner to clone an entry type it doesn't copy these ui elements over to the new (duplicated) entry type. 
Perhaps more of a feature request than a bug....

**Comment by engram-design** [comment]
Fixed in [1.2.2](https://github.com/verbb/cloner/releases/tag/1.2.2)
